### ISSUE TITLE
Cant run example: Default transport not set error

### ISSUE THREAD

**Issue by icetbr** [Zielak/cardsGame#73]
Hi there, tried to run your example and I failed.

```js
/home/ddv/dev/examples/cardGameProjects/cardsGame/packages/server/node_modules/@colyseus/core/build/Server.js:157
        throw new Error("Please provide a 'transport' layer. Default transport not set.");
        ^

Error: Please provide a 'transport' layer. Default transport not set.
    at Server.getDefaultTransport (/home/ddv/dev/examples/cardGameProjects/cardsGame/packages/server/node_modules/@colyseus/core/build/Server.js:157:15)
```

**Comment by Zielak** [comment]
Hi, thanks for taking interest in this lib :) I've just updated libraries and examples, can you try these and let me know if it worked?

For client-side: https://www.npmjs.com/package/@cardsgame/example-client-vanilla or https://www.npmjs.com/package/@cardsgame/example-client-svelte
Server-side: https://www.npmjs.com/package/@cardsgame/example-server-js

**Comment by icetbr** [comment]
Hi, sorry for the late reply. I will take a look as soon as work permit!

**Comment by icetbr** [comment]
It worked, thanks. I hade to allow connection to port 443 with 

    sudo setcap 'cap_net_bind_service=+ep' `which node`

and also had a few problems with the certificate, don't know exactly how I fixed that, maybe a rerun of the certs project plust restart.
